### PR TITLE
Fix record resolution of Update bookmarks with site.title

### LINKED ISSUE #130: sync record resolution is losing some records
tested w/ sync 1.3.2. i created a sync group on Laptop, serg joined on Android and then added some bookmarks and 2 folders on Android. Folder 1 was missing on Laptop.

this is what browser-laptop sent in RESOLVE_SYNC_RECORDS:
```
[[{"action":0,"bookmark":{"isFolder":false,"parentFolderObjectId":[124,51,88,108,115,165,9,109,93,53,46,112,45,130,98,135],"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":0,"location":"https://www.amazon.com/","title":"Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more"}},"deviceId":[1],"objectData":"bookmark","objectId":[166,251,66,54,237,237,109,129,38,184,221,40,210,51,116,165],"syncTimestamp":1499727740281},null],[{"action":0,"bookmark":{"isFolder":true,"parentFolderObjectId":[],"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":0,"location":"","title":"Folder2"}},"deviceId":[1],"objectData":"bookmark","objectId":[41,46,116,47,5,169,20,94,223,139,95,100,239,212,57,127],"syncTimestamp":1499727756517},null],[{"action":1,"bookmark":{"isFolder":true,"parentFolderObjectId":[41,46,116,47,5,169,20,94,223,139,95,100,239,212,57,127],"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":0,"location":"","title":"Folder1"}},"deviceId":[1],"objectData":"bookmark","objectId":[124,51,88,108,115,165,9,109,93,53,46,112,45,130,98,135],"syncTimestamp":1499727756573},null]]
```

This is what it received on RESOLVED_SYNC_RECORDS:
```
 [{"action":0,"bookmark":{"isFolder":false,"parentFolderObjectId":[124,51,88,108,115,165,9,109,93,53,46,112,45,130,98,135],"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":0,"location":"https://www.amazon.com/","title":"Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more"}},"deviceId":[1],"objectData":"bookmark","objectId":[166,251,66,54,237,237,109,129,38,184,221,40,210,51,116,165],"syncTimestamp":1499727740281},{"action":0,"bookmark":{"isFolder":true,"parentFolderObjectId":null,"site":{"creationTime":0,"customTitle":"","favicon":"","lastAccessedTime":0,"location":"","title":"Folder2"}},"deviceId":[1],"objectData":"bookmark","objectId":[41,46,116,47,5,169,20,94,223,139,95,100,239,212,57,127],"syncTimestamp":1499727756517}]
```

the folder1 bookmark has gone missing

### PR DESCRIPTION
**Pull request by ayumi**
Fix #130 

Test plan:
1. `yarn dist` into browser-laptop
2. change browser laptop appConfig to sync prod and join the sync profile from https://github.com/brave/sync/issues/130 on sync prod:
```
sulfuric operate wilfully poltergeist
balder playmate fica milt
unsettle headstrong madwoman compensatory
winteriest botcher giddying crustiest
```

3. after bookmarks download, there should be a Folder2 which contains Folder1.

### CODE REVIEW

**Comment by diracdeltas** [comment]
@SergeyZhukovsky found that the bookmarks appear correct on browser-laptop when you sync to the profile; it's only messed up when testing browser-laptop and android synchronously. so the test plan may not be sufficient

**Comment by diracdeltas** [comment]
i can confirm that the test plan passes without running `yarn dist`, so i think this will require synchronous testing to make sure it fixes the issue

File: test/client/recordUtil.js [hunk 1]
```diff
@@ -331,17 +331,24 @@ test('recordUtil.resolve', (t) => {
...
+
+    t.test(`${t.name}, bookmark, .isFolder, .site.title -> create folder`, (t) => {
+      const recordProps = {
+        bookmark: {
+          site: {title: 'salty title'},
+          isFolder: true
+        },
+        objectData: 'bookmark'
+      }
+      resolveToCreate(t, recordProps, recordProps, t.name)
```
Comment (diracdeltas) [inline test/client/recordUtil.js]: ++ test looks good

**Comment by diracdeltas** [comment]
synchronous test worked :woman_firefighter:
