### PR TITLE
Don't use Object.values in recordUtil

### LINKED ISSUE #147: Polyfill/work around Object.values which doesn't work on iOS <= 10.2

### PR DESCRIPTION
**Pull request by ayumi**
It doesn't work in iOS <= 10.2

Related to #147

### CODE REVIEW

File: client/recordUtil.js [hunk 1]
```diff
@@ -6,7 +6,8 @@ const serializer = require('../lib/serializer')
 const valueEquals = require('../lib/valueEquals')
 
 // ['0', '1', '2']
-module.exports.CATEGORY_IDS = Object.values(proto.categories)
+// webkit on iOS <= 10.2 does not support Object.values
+module.exports.CATEGORY_IDS = Object.keys(proto.categories).map((key) => proto.categories[key])
```
Comment (diracdeltas) [inline client/recordUtil.js]: it would be nice to make this either a global polyfill (`if (!Object.values) {Object.values = ...}`) or split it into a utility function since it is also used elsewhere (ebd7a1bf100ded50d49bf7df5dadda8cad174007)

Comment (ayumi) [inline client/recordUtil.js]: if you set `if (!Object.values) {Object.values = ...}` can it apply to all files?

Comment (diracdeltas) [inline client/recordUtil.js]: @ayumi if you add it to `client/polyfill/` and then include it in `index.html`

Comment (ayumi) [inline client/recordUtil.js]: @jhreis does that strategy work for you (adding an object.values polyfill to `client/polyfill/`)

**Comment by ayumi** [comment]
I'm going to merge and leave #147 open until the third time we run into this / we figure out the Right way to do it
