### PR TITLE
fix discrepancy between Android and Laptop RESOLVED_SYNC_RECORDS

### LINKED ISSUE #100: Wrong folders structure
Laptop browser version is 0.17.3, Android sync version 1.3.0 the latest update on f4b5d75 commit
I have an empty profile mostly on production server, there are two folders on top level `Parent1` and `Test1`. `Test1` has a one bookmark inside. Initially `Test1` folder was a subfolder of `Parent1` and was moved after. 
seatwork solely conserve misruled
sunder blandish loosed symbiot
acadia bore thanatology assumably
liftable nodding jewry correl

So on a fresh initial sync I have a correct structure, but laptop keeps showing `Test1` as a subfolder of `Parent1`. I took logs. Here what I have on `GET_EXISTING_OBJECTS`:
`[{"action":0,"deviceId":{"0":1},"objectId":{"0":196,"1":118,"2":189,"3":208,"4":37,"5":227,"6":63,"7":116,"8":229,"9":123,"10":67,"11":128,"12":84,"13":60,"14":178,"15":180},"bookmark":{"site":{"location":"https://m.facebook.com/","title":"Facebook – log in or sign up","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""},"isFolder":false,"parentFolderObjectId":[]},"objectData":"bookmark","syncTimestamp":1497571909002},{"action":0,"deviceId":{"0":1},"objectId":{"0":30,"1":44,"2":28,"3":165,"4":119,"5":114,"6":219,"7":224,"8":48,"9":58,"10":238,"11":252,"12":168,"13":155,"14":188,"15":177},"bookmark":{"site":{"location":"","title":"Test1","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""},"isFolder":true,"parentFolderObjectId":[]},"objectData":"bookmark","syncTimestamp":1497571918914},{"action":1,"deviceId":{"0":1},"objectId":{"0":196,"1":118,"2":189,"3":208,"4":37,"5":227,"6":63,"7":116,"8":229,"9":123,"10":67,"11":128,"12":84,"13":60,"14":178,"15":180},"bookmark":{"site":{"location":"https://m.facebook.com/","title":"Facebook – log in or sign up","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""},"isFolder":false,"parentFolderObjectId":{"0":30,"1":44,"2":28,"3":165,"4":119,"5":114,"6":219,"7":224,"8":48,"9":58,"10":238,"11":252,"12":168,"13":155,"14":188,"15":177}},"objectData":"bookmark","syncTimestamp":1497571918933},{"action":0,"deviceId":{"0":1},"objectId":{"0":79,"1":251,"2":234,"3":116,"4":33,"5":193,"6":72,"7":214,"8":162,"9":115,"10":189,"11":120,"12":100,"13":247,"14":121,"15":22},"bookmark":{"site":{"location":"","title":"Parent1","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""},"isFolder":true,"parentFolderObjectId":[]},"objectData":"bookmark","syncTimestamp":1497571975338},{"action":1,"deviceId":{"0":1},"objectId":{"0":30,"1":44,"2":28,"3":165,"4":119,"5":114,"6":219,"7":224,"8":48,"9":58,"10":238,"11":252,"12":168,"13":155,"14":188,"15":177},"bookmark":{"site":{"location":"","title":"Test1","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""},"isFolder":true,"parentFolderObjectId":{"0":79,"1":251,"2":234,"3":116,"4":33,"5":193,"6":72,"7":214,"8":162,"9":115,"10":189,"11":120,"12":100,"13":247,"14":121,"15":22}},"objectData":"bookmark","syncTimestamp":1497571975376},{"action":1,"deviceId":{"0":0},"objectId":{"0":30,"1":44,"2":28,"3":165,"4":119,"5":114,"6":219,"7":224,"8":48,"9":58,"10":238,"11":252,"12":168,"13":155,"14":188,"15":177},"bookmark":{"hideInToolbar":false,"isFolder":true,"parentFolderObjectId":{"0":79,"1":251,"2":234,"3":116,"4":33,"5":193,"6":72,"7":214,"8":162,"9":115,"10":189,"11":120,"12":100,"13":247,"14":121,"15":22},"site":{"location":"","title":"Test1","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""}},"objectData":"bookmark","syncTimestamp":1497572014030},{"action":1,"deviceId":{"0":1},"objectId":{"0":30,"1":44,"2":28,"3":165,"4":119,"5":114,"6":219,"7":224,"8":48,"9":58,"10":238,"11":252,"12":168,"13":155,"14":188,"15":177},"bookmark":{"site":{"location":"","title":"Test1","customTitle":"","lastAccessedTime":0,"creationTime":0,"favicon":""},"isFolder":true,"parentFolderObjectId":[]},"objectData":"bookmark","syncTimestamp":1497572038641}]`

------------------------------------------
After that I send that on `SEND_RESOLVED_RECORDS`:
`[[{ action: 0, deviceId: [1], objectId: [196, 118, 189, 208, 37, 227, 63, 116, 229, 123, 67, 128, 84, 60, 178, 180], objectData: 'bookmark', bookmark:{ site:{ location: "https://m.facebook.com/", title: "Facebook – log in or sign up", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: false, parentFolderObjectId: null} }, null], [{ action: 0, deviceId: [1], objectId: [30, 44, 28, 165, 119, 114, 219, 224, 48, 58, 238, 252, 168, 155, 188, 177], objectData: 'bookmark', bookmark:{ site:{ location: "", title: "Test1", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: true, parentFolderObjectId: null} }, null], [{ action: 1, deviceId: [1], objectId: [196, 118, 189, 208, 37, 227, 63, 116, 229, 123, 67, 128, 84, 60, 178, 180], objectData: 'bookmark', bookmark:{ site:{ location: "https://m.facebook.com/", title: "Facebook – log in or sign up", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: false, parentFolderObjectId: [30, 44, 28, 165, 119, 114, 219, 224, 48, 58, 238, 252, 168, 155, 188, 177]} }, null], [{ action: 0, deviceId: [1], objectId: [79, 251, 234, 116, 33, 193, 72, 214, 162, 115, 189, 120, 100, 247, 121, 22], objectData: 'bookmark', bookmark:{ site:{ location: "", title: "Parent1", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: true, parentFolderObjectId: null} }, null], [{ action: 1, deviceId: [1], objectId: [30, 44, 28, 165, 119, 114, 219, 224, 48, 58, 238, 252, 168, 155, 188, 177], objectData: 'bookmark', bookmark:{ site:{ location: "", title: "Test1", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: true, parentFolderObjectId: [79, 251, 234, 116, 33, 193, 72, 214, 162, 115, 189, 120, 100, 247, 121, 22]} }, null], [{ action: 1, deviceId: [0], objectId: [30, 44, 28, 165, 119, 114, 219, 224, 48, 58, 238, 252, 168, 155, 188, 177], objectData: 'bookmark', bookmark:{ site:{ location: "", title: "Test1", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: true, parentFolderObjectId: [79, 251, 234, 116, 33, 193, 72, 214, 162, 115, 189, 120, 100, 247, 121, 22]} }, null], [{ action: 1, deviceId: [1], objectId: [30, 44, 28, 165, 119, 114, 219, 224, 48, 58, 238, 252, 168, 155, 188, 177], objectData: 'bookmark', bookmark:{ site:{ location: "", title: "Test1", customTitle: "", favicon: "", lastAccessedTime: 0, creationTime: 0}, isFolder: true, parentFolderObjectId: null} }, null]]`

---------------------------------------------
and that is what I receive on `RESOLVED_RECORDS`:
`[{"action":0,"deviceId":[1],"objectId":[196,118,189,208,37,227,63,116,229,123,67,128,84,60,178,180],"objectData":"bookmark","bookmark":{"site":{"location":"https://m.facebook.com/","title":"Facebook – log in or sign up","customTitle":"","favicon":"","lastAccessedTime":0,"creationTime":0},"isFolder":false,"parentFolderObjectId":[30,44,28,165,119,114,219,224,48,58,238,252,168,155,188,177]}},{"action":0,"deviceId":[1],"objectId":[30,44,28,165,119,114,219,224,48,58,238,252,168,155,188,177],"objectData":"bookmark","bookmark":{"site":{"location":"","title":"Test1","customTitle":"","favicon":"","lastAccessedTime":0,"creationTime":0},"isFolder":true,"parentFolderObjectId":null}},{"action":0,"deviceId":[1],"objectId":[79,251,234,116,33,193,72,214,162,115,189,120,100,247,121,22],"objectData":"bookmark","bookmark":{"site":{"location":"","title":"Parent1","customTitle":"","favicon":"","lastAccessedTime":0,"creationTime":0},"isFolder":true,"parentFolderObjectId":null}}]`

-----
You can see that it is a correct structure on `RESOLVED_RECORDS`. I have no idea why laptop does it different and more then that iOS also does the same way as laptop.

### LINKED ISSUE #107: Change to Parent bookmark folder on Android is not sycned to laptop or iOS device
Did you search for similar issues before submitting this one?
Yes

Description:
Changing the parent folder of a bookmarks folder does not sync to laptop, but does sync android-android.

Pyramid 0 is Mac Laptop
Pyramid 1 is Nexus 5
Pyramid 2 is Galaxy S4

Device Details:

Install Type(ARM, x86): Arm
Device(Phone, Tablet, Phablet): Mac Laptop, Nexus5, Galaxy S4
Android Version: Nexus 5 is 5.1, Galaxy S4 is 5.0.1

Brave Version:
Android version is 1.0.23beta
Laptop version is 0.17.2

Steps to reproduce:
0. Laptop and both Androids do not have any bookmarks (clean installs)
1. Create sync group on mac laptop
2. Join sync group - joined on Android devices 1&2 (nexus and galaxy respectively)
3. On device 1 (Nexus), create a bookmark at ‘Mobile Bookmarks’ level, create a folder which contains 2 different bookmarks.
4. Folder and all bookmarks are synced to laptop and android device 2
5. On device 1 (nexus), create a new folder as the parent folder for the folder created in step 3 (To do this - open bookmarks, tap on 3 dots on the folder, select edit, tap on mobile bookmarks, tap on new folder, put name, select checkmark in upper right corner, nav back to bookmarks).
6. Change is synced to laptop and android device 2
7. Back on device 1, change the parent bookmark. (to do this: open bookmarks again, tap on folder created in step 5, tap on 3 dots for the sub folder (this is the folder which was created in step 3). select edit. change the parent folder to be mobile bookmarks instead of the folder created in step 5. nav back to bookmarks.)
8. The parent folder change is synced to android device 2, but not to laptop.

Actual Behavior
Laptop still displays:
Folder from Step 5 > Folder from Step 3 > 2 bookmarks created in step 3.

Expected Behavior
Laptop should reflect the change in bookmark parent folder.

Is this an issue with Beta build?
Yes

Is this an issue in the currently released version?
No

Can this issue be consistently reproduced?
Yes

Extra QA steps:
1. Repeat steps 2-8 with an iOS device. Parent folder change from Android is not updated on iOS device either.
2.
3.

Website problems only:

did you check with Brave Shields down?
did you check in Chrome for same behavior?

Screenshot if needed:
Laptop (incorrect folder structure):
screen shot 2017-06-14 at 4 25 30 pm

Nexus 5 and Galaxy S4 (correct folder structure):
screenshot_2017-06-14-16-25-15

Any related issues:

### PR DESCRIPTION
**Pull request by diracdeltas**
browser-laptop sends 'parentFolderObjectId: []' for top-level folders whereas
android sends 'parentFolderObjectId: null'. for consistency, they should just
be normalized to be the same value.

fix #107 
TODO check if this fixes #100 

test plan:
1. tests should pass
2. for serg: check out this pull request, then run `yarn dist` to build and copy the sync library over to browser-laptop. in browser-laptop, edit `js/constants/appConfig` and change `isProduction` to true. then sync to "whisker..." group in browser-laptop. the hierarchy should be the same on android and laptop.

### CODE REVIEW

File: test/client/recordUtil.js [hunk 1]
```diff
@@ -370,7 +370,20 @@ test('recordUtil.resolve', (t) => {
 })
 
 test('recordUtil.resolveRecords()', (t) => {
-  t.plan(4)
+  t.plan(5)
+
+  t.test(`${t.name} resolves same data cross-platform on laptop and android`, (t) => {
+    t.plan(1)
+    const androidRecordsAndExistingObjects = require('./data/resolveAndroid').data
```
Comment (ayumi) [inline test/client/recordUtil.js]: minor: I like to call test data "fixtures"

Comment (ayumi) [inline test/client/recordUtil.js]: Minor: It may help to add a comment explaining how the `./data/resolveAndroid` and `./data/resolveLaptop` fixtures had been generated, such that someone could go and regenerate them.

File: client/recordUtil.js [hunk 2]
```diff
@@ -262,6 +273,12 @@ const mergeRecords = (recordsAndObjects) => {
  */
 module.exports.resolveRecords = (recordsAndExistingObjects) => {
   let resolvedRecords = []
+  recordsAndExistingObjects.forEach((item) => {
+    if (item) {
```
Comment (ayumi) [inline client/recordUtil.js]: is the `item` truthiness check necessary? in `mergeRecords()` we do a similar `forEach()` while assuming the values of item[0] and item[1].

File: test/client/recordUtil.js (hunk 1 above)
Comment (diracdeltas) [inline test/client/recordUtil.js]: ++

File: client/recordUtil.js (hunk 2 above)
Comment (diracdeltas) [inline client/recordUtil.js]: maybe not necessary at the moment but better to be safe here since resolveRecords is an exported function

**Comment by SergeyZhukovsky** [comment]
It looks good. I verified it with the current pull request and laptop syncs a folder structure properly now. Thanks!
